"""add notice table

Revision ID: 353712a8d51d
Revises: 
Create Date: 2017-09-19 15:56:26.347357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '353712a8d51d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.Column('key', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('strategy_name', sa.CHAR(length=100), nullable=False),
    sa.Column('scene_name', sa.CHAR(length=100), nullable=False),
    sa.Column('check_type', sa.CHAR(length=100), nullable=False),
    sa.Column('decision', sa.CHAR(length=100), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('expire', sa.BigInteger(), nullable=False),
    sa.Column('last_modified', sa.BigInteger(), nullable=True),
    sa.Column('variable_values', sa.BLOB(), nullable=False),
    sa.Column('geo_province', sa.CHAR(length=100), nullable=True),
    sa.Column('geo_city', sa.CHAR(length=100), nullable=True),
    sa.Column('test', sa.SMALLINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notice')
    # ### end Alembic commands ###
