"""add notice keys

Revision ID: e80bd4824994
Revises: 353712a8d51d
Create Date: 2017-10-27 14:14:46.221186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e80bd4824994'
down_revision = '353712a8d51d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notice', sa.Column('notice_keys', sa.BLOB(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notice', 'notice_keys')
    # ### end Alembic commands ###
