"""add timestamp index

Revision ID: e84cb2206960
Revises: e80bd4824994
Create Date: 2017-11-04 20:26:30.991662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e84cb2206960'
down_revision = 'e80bd4824994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_timestamp', 'notice', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_timestamp', table_name='notice')
    # ### end Alembic commands ###
